code --install-extension ajshort.latex-preview
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bungcip.better-toml
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.jupyter
code --install-extension EditorConfig.EditorConfig
code --install-extension Gimly81.matlab
code --install-extension Ikuyadeu.r
code --install-extension James-Yu.latex-workshop
code --install-extension MS-CEINTL.vscode-language-pack-pt-BR
code --install-extension ms-python.anaconda-extension-pack
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.sublime-keybindings
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension puorc.awesome-vhdl
code --install-extension rashwell.tcl
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-portuguese-brazilian
